export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const FETCH_USER = 'FETCH_USER';

export const IS_LOADING = 'IS_LOADING';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_CODE = 'SET_CODE';

export const SET_POST = 'SET_POST';
export const SET_POST_VISITED = 'SET_POST_VISITED';
export const SET_POST_DISMISSED = 'SET_POST_DISMISSED';
export const SET_ALL_POSTS_DISMISSED = 'SET_ALL_POSTS_DISMISSED';

export const SET_IS_MENU_OPEN = 'SET_IS_MENU_OPEN';